on:
  push:
    branches: main
  pull_request:
    branches: main

name: ci

jobs:

  # smoke:

  #   runs-on: ubuntu-latest

  #   env:
  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  #     R_KEEP_PKG_SOURCE: yes

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: r-lib/actions/setup-pandoc@v2

  #     - uses: r-lib/actions/setup-r@v2
  #       with:
  #         use-public-rspm: true

  #     - uses: r-lib/actions/setup-r-dependencies@v2
  #       with:
  #         extra-packages: any::rcmdcheck
  #         needs: check

  #     - uses: r-lib/actions/check-r-package@v2
  #       with:
  #         upload-snapshots: true

  # check:

  #   needs: smoke

  #   if: github.event_name != 'pull_request'

  #   uses: ./.github/workflows/check.yml

  #   secrets: inherit

  # coverage:

  #   needs: smoke

  #   uses: ./.github/workflows/coverage.yml

  #   secrets: inherit

  # lint:

  #   needs: smoke

  #   uses: ./.github/workflows/lint.yml

  #   secrets: inherit
  
  deploy:

    #needs: smoke
  
    uses: ./.github/workflows/deploy-app.yml
  
    secrets: inherit

  # pkgdown:

  #   needs: smoke

  #   if: github.event_name != 'pull_request'

  #   uses: ./.github/workflows/pkgdown.yml

  #   secrets: inherit

  #   permissions:
  #     contents: write
