on:
  workflow_call:
  
name: deploy
  
jobs:
  
    deploy:
  
      runs-on: ubuntu-latest
  
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        CONNECT_USER: ${{ secrets.CONNECT_USER }}
        CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
  
      steps:
        - uses: actions/checkout@v3
  
        - uses: r-lib/actions/setup-pandoc@v2
  
        - uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true
  
        - uses: r-lib/actions/setup-renv@v2
          with:
            # renv.lock is created inside inst/examples
            # to capture all deps from all apps. 
            # We must create a symlink in the package root
            # so packages are installed in the right location
            # for the next step.
            working-directory: "."
  
        - name: Deploy app
          run: |
            renv::status()
            renv::install("blockr-org/blockr")
            # Have to manually install blockr because
            # it is ignore by renv restore, despite
            # being in the lock file ...
            source("deploy/deploy-workflow.R")
            app_path <- "inst/examples/add-blocks"
            deploy_app_rsc("blockr-demo", app_path)
          shell: Rscript {0}
