on:
  workflow_call:

name: publish

jobs:

  publish:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.BLOCKR_PAT }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'release'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::shinytest2
            any::knitr
            any::rmarkdown

      - name: Generate screenshot
        run: Rscript site/scripts/generate_screenshot.R

      - name: Compile assets
        run: Rscript site/scripts/compile_assets.R

      - name: Render Quarto website
        run: quarto render site/_assets

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: site/_site
          clean: false
